// takedown.js
export const generateTakedownEmail = ({ brand, candidate, evidenceUrl, apkUrl=null }) => {
  const subject = `Takedown request: Impersonator app detected for ${brand.brandName || brand}`;
  const body = `
Hello ${brand.brandName || "Brand Team"},

We detected an app that appears to impersonate your brand.

Candidate app:
  - Reported package: ${candidate.package || "N/A"}
  - Reported app name: ${candidate.app_name || "N/A"}
  - Detection score: ${candidate.score || "N/A"}
  - Reasons: ${candidate.reasons ? candidate.reasons.join(", ") : "N/A"}

Evidence:
  - Evidence JSON: ${evidenceUrl}
  - Evidence HTML: ${evidenceUrl ? evidenceUrl.replace(".json", ".html") : "N/A"}
  - APK (if available): ${apkUrl || "N/A"}

Summary:
This app exhibits impersonation signals (name/package similarity low, certificate mismatch, suspicious permissions, strings or native libs). Please review and action per your takedown process.

This request is auto-generated by AppSentinel – attach the evidence kit as necessary.

Regards,
AppSentinel Automated Reports
`;

  return { subject, body };
};
